name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request: # Trigger on pull requests to main branch
    branches:
      - main
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:

  lint:
    name: Code linting
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # or 'zulu', 'adopt', etc.
          java-version: '11'
          cache: 'maven'

      # Check Linting with Maven Formatter Plugin
      - name: Run Formatter Validation
        run: mvn formatter:validate

  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # or 'zulu', 'adopt', etc.
          java-version: '11'
          cache: 'maven'

      # Build the project using Maven
      - name: Build with Maven
        run: mvn package -DskipTests

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [lint] # Allow tests to run after linting
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # or 'zulu', 'adopt', etc.
          java-version: '11'
          cache: 'maven'
      - name: Run Tests
        run: mvn test

# Will come later
# coverage:
#   name: code coverage
#   runs-on: ubuntu-latest
#   needs: tests
