name: CI Pipeline
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:

  lint:
    name: Code linting
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # or 'zulu', 'adopt', etc.
          java-version: '11'
          cache: 'maven'

      # Check Linting with Maven Formatter Plugin
      - name: Run Formatter Validation
        run: mvn formatter:validate

  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # or 'zulu', 'adopt', etc.
          java-version: '11'
          cache: 'maven'

      # Build the project using Maven
      - name: Build with Maven
        run: mvn package -DskipTests

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [lint] # Allow tests to run after linting
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # or 'zulu', 'adopt', etc.
          java-version: '11'
          cache: 'maven'
      - name: Run Tests
        run: mvn test

  coverage:
    name: Code Coverage Report
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Generate JaCoCo Report #generate code coverage report using JaCoCo
        run: mvn test jacoco:report

      - name: Upload Coverage Report #upload code coverage report in GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn verify sonar:sonar -Dsonar.projectKey=INFOM126-Automated-Software-Engineering_2048-groupe-hms -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN